### ISSUE TITLE
404 on public folder

### ISSUE THREAD

**Issue by jaxoncreed** [inrupt/wac-ldp#136] opened 2019-07-30 21:24 UTC
Request:

```
curl -X GET \
  https://otherjackson.api.swype.io/public \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Cache-Control: no-cache' \
  -H 'Host: otherjackson.api.swype.io' \
  -H 'Postman-Token: ff82097c-ff78-42d5-83e7-88b7a2f867c0,68118cbb-6d88-4ede-91e5-c54da5d16487' \
  -H 'User-Agent: PostmanRuntime/7.15.2' \
  -H 'authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL290aGVyamFja3Nvbi5hcGkuc3d5cGUuaW8iLCJhdWQiOiJodHRwczovL290aGVyamFja3Nvbi5hcGkuc3d5cGUuaW8iLCJleHAiOjE1NjQ1MjUwNTUsImlhdCI6MTU2NDUyMTQ1NSwiaWRfdG9rZW4iOiJleUpoYkdjaU9pSlNVekkxTmlJc0luUjVjQ0k2SWtwWFZDSXNJbXRwWkNJNkltdGxlWE4wYjNKbExVTklRVTVIUlMxTlJTSjkuZXlKemRXSWlPaUpvZEhSd2N6b3ZMMjkwYUdWeWFtRmphM052Ymk1aGNHa3VjM2Q1Y0dVdWFXOHZjSEp2Wm1sc1pTOWpZWEprSTIxbElpd2libTl1WTJVaU9pSnhVVEY1WlRsbE0yMHdSMms1UTFGT1IzcFVOek5VYlZSeE9VdHVZVVJMZDFGTVRtdFJTazF2WkVaM0lpd2ljMmxrSWpvaVptUTJaVGN3Tm1RdE5qTXlNQzAwTVRNMExXRTJaREF0WmpJM09EVTJOMkUzTUdRM0lpd2lZWFJmYUdGemFDSTZJazQ0YURSSGRWRnJhMVZ5ZVhOZlZsUjNlRzU0ZVhjaUxDSnpYMmhoYzJnaU9pSm5VWGN5WDBseVIwOXRhM2RVTm14SExWSlViWFZuSWl3aVkyNW1JanA3SW1Gc1p5STZJbEpUTWpVMklpd2laU0k2SWtGUlFVSWlMQ0psZUhRaU9uUnlkV1VzSW10bGVWOXZjSE1pT2xzaWRtVnlhV1o1SWwwc0ltdDBlU0k2SWxKVFFTSXNJbTRpT2lKM1pEWndPVkp1YUhkc2VHaDRXSHBSUWtOVFRqUjFZbHBNVm5ReVJHTkRZbXB6VVdKbVJGWXhUMkV0Y25GdU1XbE5XRFp0YUhndFRVdHFTVlpCVURaNWRWbDRNMlowWlhjNE9FNWZVV2x1YjJrMk1GRk9TVTgzU1RSbmIyOUdWMEp6T1RsVGFrRmlZM0JMZGkxeWVETkxRVWR4UTBwTVgyaGlkbTlCWVhwcFNWOW5aWFozWVZsd1dtRlNMWE0yYkZob1QyNU9RM0pUTW5KSFdEWmtNRzgzV1ZaRFlUUnRNSFJaTVU0eWVXWlZXa3N5VDJoWVJFSnBOMWxFWWtORmNESmZNRU0xUTNaaWNEbHZaSFJsUVZCNmJFaElZbk5PYnpWaU5GZHFMVGQ0TFdsYVJHUTBZa05NTkhoTWFFOWlPRzVYWlZFNFp5MU9jR2RzVFUxSmJqWkdSVGRwVW1WUmExY3pXVE41YkRsbFF6aHhZV2RNY21oS1pXbHNaVVV5UVhCUk5qTXRaRU5ZV0ZCWFptZFlZeTFFVDJwVlZXVlZZM1ZLZDBGeFRuWnphMVZIY0RkR2MyOUZOVkZNVlRSVmVsUXpaM3B4T1hjaWZTd2lZWFZrSWpvaWFIUjBjSE02THk5dmRHaGxjbXBoWTJ0emIyNHVZWEJwTG5OM2VYQmxMbWx2SWl3aVpYaHdJam94TlRZME5USTBNakF4TENKcFlYUWlPakUxTmpRMU1qQTJNREVzSW1semN5STZJbWgwZEhCek9pOHZZWEJwTG5OM2VYQmxMbWx2SW4wLmgwMEg0dU5WUUp2OFpVZXY0ZnI1cE92QW9pZUpWeGx6c3ZMQjVvN21ObndRZU1JeHNMc1lpa1dZd1pCRmZpYmduWHJ5Mm9jemwwNzcyS21rMlVUSmtURlJGVlRIUFVRVVpkT1FCSWx3cy1pNUZhaFVzVVo4ZDlTeG1lV0g1S3B2RkY1MDNEYy1ZNWxmUW1hVThZSS1wRFVDVDV4S2J3UjRJY2l4b3M1ZWtGel95QVBHeTllb1VaUmlOZWlrS01weFFDMTU3bFNGeXBkSHhUR1VadVhqak5SVTRvS0NWRDNoejkyTER5ZmtydHQtRTRpTVVyRUNnaWQyRm43WkViZHJ0LUlyWk4wMG5VSTNXVTlGRUFOUTN3M19ES1VoNlJIaTBnOG4tZlpwVWtoZGp3THBjbTRma1JyaDFwa3hrX3liWF8xZ0txcHV0dXhreDlCVXZkbDF5ZyIsInRva2VuX3R5cGUiOiJwb3AifQ.RaU2HCllgWrkZV1cfasTBxWqosnGJ6XFaljwV2vk9wNJ1HCOsc6DO1Ljvlu40aEgJfWi28v6VvpnoixqtsEgQm9gxyr1SdSYwgAA67EGzAOdVWILTG_Ur0sSEJiQeegt4c8wUDz5xgYNT5x-jWatNBqNXzXi4lgd4K9Ow8U3UKdzoY8PALYoEaAJ1WUJS2-P7GCHX8f7JFdE6tD_Z5NEPscCaiO_TtTu6-WnK-B28wufcC6VWnERYwWiqPyCk2aAoQoyrWXXl5fuZ1a0i6QWAbVF3L2BPJB6-fWVG-r_4BtyH-nNB3jkFyMYIYA5pB1Lwi9VQb9hqaNvbG-YpKKPzg' \
  -H 'cache-control: no-cache'
```

The public folder does exist (in redis cli):
```
127.0.0.1:6379> keys v1/otherjackson.api.swype.io/public*
1) "v1/otherjackson.api.swype.io/public/"
2) "v1/otherjackson.api.swype.io/public/.acl"
```

**Comment by jaxoncreed** [comment] 2019-07-30 21:53
Note that the following DOES work:
```
curl -X GET \
  https://otherjackson.api.swype.io/public/ \
  -H 'Accept: image/*;q=0.9, */*;q=0.1, application/rdf+xml;q=0.9, application/xhtml+xml, text/xml;q=0.5, application/xml;q=0.5, text/html;q=0.9, text/plain;q=0.5, text/n3;q=1.0, text/turtle;q=1' \
  -H 'Accept-Encoding: gzip, deflate, br' \
  -H 'Accept-Language: en-US,en;q=0.5' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Host: otherjackson.api.swype.io' \
  -H 'Postman-Token: 92482693-e5e9-420f-9dd4-08109f513f8e,eb3a40f9-c6be-4776-8333-0413bff45742' \
  -H 'Referer: https://otherjackson.api.swype.io/public/' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:68.0) Gecko/20100101 Firefox/68.0' \
  -H 'authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL290aGVyamFja3Nvbi5hcGkuc3d5cGUuaW8iLCJhdWQiOiJodHRwczovL290aGVyamFja3Nvbi5hcGkuc3d5cGUuaW8iLCJleHAiOjE1NjQ1MjcxMDAsImlhdCI6MTU2NDUyMzUwMCwiaWRfdG9rZW4iOiJleUpoYkdjaU9pSlNVekkxTmlJc0luUjVjQ0k2SWtwWFZDSXNJbXRwWkNJNkltdGxlWE4wYjNKbExVTklRVTVIUlMxTlJTSjkuZXlKemRXSWlPaUpvZEhSd2N6b3ZMMjkwYUdWeWFtRmphM052Ymk1aGNHa3VjM2Q1Y0dVdWFXOHZjSEp2Wm1sc1pTOWpZWEprSTIxbElpd2libTl1WTJVaU9pSnhVVEY1WlRsbE0yMHdSMms1UTFGT1IzcFVOek5VYlZSeE9VdHVZVVJMZDFGTVRtdFJTazF2WkVaM0lpd2ljMmxrSWpvaVptUTJaVGN3Tm1RdE5qTXlNQzAwTVRNMExXRTJaREF0WmpJM09EVTJOMkUzTUdRM0lpd2lZWFJmYUdGemFDSTZJazQ0YURSSGRWRnJhMVZ5ZVhOZlZsUjNlRzU0ZVhjaUxDSnpYMmhoYzJnaU9pSm5VWGN5WDBseVIwOXRhM2RVTm14SExWSlViWFZuSWl3aVkyNW1JanA3SW1Gc1p5STZJbEpUTWpVMklpd2laU0k2SWtGUlFVSWlMQ0psZUhRaU9uUnlkV1VzSW10bGVWOXZjSE1pT2xzaWRtVnlhV1o1SWwwc0ltdDBlU0k2SWxKVFFTSXNJbTRpT2lKM1pEWndPVkp1YUhkc2VHaDRXSHBSUWtOVFRqUjFZbHBNVm5ReVJHTkRZbXB6VVdKbVJGWXhUMkV0Y25GdU1XbE5XRFp0YUhndFRVdHFTVlpCVURaNWRWbDRNMlowWlhjNE9FNWZVV2x1YjJrMk1GRk9TVTgzU1RSbmIyOUdWMEp6T1RsVGFrRmlZM0JMZGkxeWVETkxRVWR4UTBwTVgyaGlkbTlCWVhwcFNWOW5aWFozWVZsd1dtRlNMWE0yYkZob1QyNU9RM0pUTW5KSFdEWmtNRzgzV1ZaRFlUUnRNSFJaTVU0eWVXWlZXa3N5VDJoWVJFSnBOMWxFWWtORmNESmZNRU0xUTNaaWNEbHZaSFJsUVZCNmJFaElZbk5PYnpWaU5GZHFMVGQ0TFdsYVJHUTBZa05NTkhoTWFFOWlPRzVYWlZFNFp5MU9jR2RzVFUxSmJqWkdSVGRwVW1WUmExY3pXVE41YkRsbFF6aHhZV2RNY21oS1pXbHNaVVV5UVhCUk5qTXRaRU5ZV0ZCWFptZFlZeTFFVDJwVlZXVlZZM1ZLZDBGeFRuWnphMVZIY0RkR2MyOUZOVkZNVlRSVmVsUXpaM3B4T1hjaWZTd2lZWFZrSWpvaWFIUjBjSE02THk5dmRHaGxjbXBoWTJ0emIyNHVZWEJwTG5OM2VYQmxMbWx2SWl3aVpYaHdJam94TlRZME5USTBNakF4TENKcFlYUWlPakUxTmpRMU1qQTJNREVzSW1semN5STZJbWgwZEhCek9pOHZZWEJwTG5OM2VYQmxMbWx2SW4wLmgwMEg0dU5WUUp2OFpVZXY0ZnI1cE92QW9pZUpWeGx6c3ZMQjVvN21ObndRZU1JeHNMc1lpa1dZd1pCRmZpYmduWHJ5Mm9jemwwNzcyS21rMlVUSmtURlJGVlRIUFVRVVpkT1FCSWx3cy1pNUZhaFVzVVo4ZDlTeG1lV0g1S3B2RkY1MDNEYy1ZNWxmUW1hVThZSS1wRFVDVDV4S2J3UjRJY2l4b3M1ZWtGel95QVBHeTllb1VaUmlOZWlrS01weFFDMTU3bFNGeXBkSHhUR1VadVhqak5SVTRvS0NWRDNoejkyTER5ZmtydHQtRTRpTVVyRUNnaWQyRm43WkViZHJ0LUlyWk4wMG5VSTNXVTlGRUFOUTN3M19ES1VoNlJIaTBnOG4tZlpwVWtoZGp3THBjbTRma1JyaDFwa3hrX3liWF8xZ0txcHV0dXhreDlCVXZkbDF5ZyIsInRva2VuX3R5cGUiOiJwb3AifQ.Ilf_XdYB-2GLKGD8-1RfZkotaBJFHZ249Hwutx0MzyfXJKNb8fitTnVoq3K41xWt33QKCsYY6iKp1vGcjwltpA79IJeFsODDTt3cY2BfxqNrSWiRUd3wqSsBXL8LDFfonRmryxq7ZnW3ksFp6MJsPKmPvcvZqUktJiFJRLXgtcCaX4O4No6KGHjwB4T-bZBR2g5vGDjV1O_rsQmjekhKm3hOdixM6C1vFJqODlmccN2nB79DxFy7Udw_-ttcgKrOGKbUhNYaSgun7uaeMtZcWWO_BWP3VCctR-6MOpZjfSIWSUnT2TIgOGrbrAWCukJjsctuqZmdMI6F83On0L_Qdw' \
  -H 'cache-control: no-cache'
```

**Comment by jaxoncreed** [comment] 2019-07-30 22:25
It's the trailing slash. 404 when there is no trailing slash. The databrowser makes requests without a trailing slash for nested folders.

**Comment by jaxoncreed** [comment] 2019-07-30 22:26
Tim says that this should send a redirect to the one with the trailing slash

**Comment by michielbdejong** [comment] 2019-07-31 08:46
ah ok. so then we can reopen https://github.com/inrupt/wac-ldp/issues/13 and mark this as a duplicate of that.

**Closed by michielbdejong** 2019-07-31 08:46 UTC
