### ISSUE TITLE
Access Denied to Public folder

### ISSUE THREAD

**Issue by jaxoncreed** [inrupt/wac-ldp#135] opened 2019-07-30 21:21 UTC
Request:

```
curl -X GET \
  https://otherjackson.api.swype.io/public \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Cache-Control: no-cache' \
  -H 'Host: otherjackson.api.swype.io' \
  -H 'Postman-Token: 57a4978a-bce1-444b-9497-e158357617d4,44f40dd5-e634-47b8-9d4f-cd829d4f7e4e' \
  -H 'User-Agent: PostmanRuntime/7.15.2' \
  -H 'cache-control: no-cache'
```

Public folder .acl:
```
{"contentType":"text/turtle","body":"@prefix acl: <http://www.w3.org/ns/auth/acl#>.
@prefix  foaf:  <http://xmlns.com/foaf/0.1/>.
<#owner>
  a acl:Authorization;
  acl:agent <https://otherjackson.api.swype.io/profile/card#me>;
  acl:accessTo <./>;
  acl:default <./>;
  acl:mode
    acl:Read, acl:Write, acl:Control.
<#public>
  a acl:Authorization;
  acl:agent foaf:Agent;
  acl:accessTo <./>;
  acl:default <./>;
  acl:mode
    acl:Read.","etag":"VWhoIwQzLSrqY0C9QTX6cQ==","rdfType":1}
```

**Comment by jaxoncreed** [comment] 2019-07-30 22:27
This is caused by a similar problem to https://github.com/inrupt/wac-ldp/issues/136#issuecomment-516619142

There should be a redirect to the one with the trailing slash

**Comment by michielbdejong** [comment] 2019-07-31 08:45
should there, though?

**Comment by michielbdejong** [comment] 2019-07-31 08:49
ah, yes there should, see https://github.com/solid/solid-spec/issues/208. So then this is a duplicate of #13 as well. Will fix it there!

**Closed by michielbdejong** 2019-07-31 08:49 UTC
