### ISSUE TITLE
Internal server error on profile update

### ISSUE THREAD

**Issue by jaxoncreed** [inrupt/wac-ldp#134] opened 2019-07-30 20:55 UTC
The request:
```
curl -X PATCH \
  https://otherjackson.api.swype.io/profile/card \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Length: 118' \
  -H 'Host: otherjackson.api.swype.io' \
  -H 'Postman-Token: 9938c6ed-5051-4126-8a9a-eff45172ea7c,81c9fcee-06b6-45b7-a0c7-e889a95081f5' \
  -H 'User-Agent: PostmanRuntime/7.15.2' \
  -H 'authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL290aGVyamFja3Nvbi5hcGkuc3d5cGUuaW8iLCJhdWQiOiJodHRwczovL290aGVyamFja3Nvbi5hcGkuc3d5cGUuaW8iLCJleHAiOjE1NjQ1MjM1MDIsImlhdCI6MTU2NDUxOTkwMiwiaWRfdG9rZW4iOiJleUpoYkdjaU9pSlNVekkxTmlJc0luUjVjQ0k2SWtwWFZDSXNJbXRwWkNJNkltdGxlWE4wYjNKbExVTklRVTVIUlMxTlJTSjkuZXlKemRXSWlPaUpvZEhSd2N6b3ZMMjkwYUdWeWFtRmphM052Ymk1aGNHa3VjM2Q1Y0dVdWFXOHZjSEp2Wm1sc1pTOWpZWEprSTIxbElpd2libTl1WTJVaU9pSlpXRlZDWmtKblVraGlXbDlVUjBWekxUTkdOek40UjFKb1EybGliVmgwZFhZNFVraHlRWFJpVDFsRklpd2ljMmxrSWpvaVkyTTBPR1ZtWlRFdE0ySmtOQzAwWkRobExXSTJNakF0TVROaFl6TmlNRGczTWpJeklpd2lZWFJmYUdGemFDSTZJa2c0VWpsMlFWUkpNVEEyTTI1d09UQjVTVkJmVlVFaUxDSnpYMmhoYzJnaU9pSjRhRUl5UlcxSlJ6UmFNMHBOTkdNeU16QXRNa1puSWl3aVkyNW1JanA3SW1Gc1p5STZJbEpUTWpVMklpd2laU0k2SWtGUlFVSWlMQ0psZUhRaU9uUnlkV1VzSW10bGVWOXZjSE1pT2xzaWRtVnlhV1o1SWwwc0ltdDBlU0k2SWxKVFFTSXNJbTRpT2lKNlNtTnRaVXhRWmtsdlRuQnVjVXhOWWxKcWQweElkRmszYXpkSlVuSktVREF0VVdWSGEwUm5kVGRsTVhRNFQycDFRbUpTTUdGZlUzYzVXVEpWTm1GUk1teDBRVmhXVFhZNGJrTndaRGRsWldwQlJGSmhRV1p6VlVKME9IWlZORTlLYzFsdk9UTTFWbmh1UVdOSWNrTm1NVzl4Y1RCbGVUZ3RkMHhHYlZCMlRVZDFVVmMxVjI5bVpFdHFWREZ6WjBJNWFYbE5WM3BxUTJKSFRHMXpSREkxYWtaNWIwRlNjVEZEWkhWbFpuTjRjekJrTTJGck4yeEJaRW81T1ROSVdrRjNWVUZVUjFvM05tWTFablZDZVRWc2FqTllWa0ZLTUhKcVZqZHNPV2RRYlUxa2RXbHdkV2w1VDFweGNVTkplR05RV0RSR1pIUmtRVmgyVjJNNFZsZExaRU5tVWtwRk1sOVhhRFJqU0hwNE1HcE5SbHBQUjJ0aGVUSXlXR2RXYzFKbmFEQkZaVVJQVm1GWGQwbzBaRFU0TTNWV2NFdFNhek5vUm10dGQzRjNPVlZyZGpkb1dtNUVXbEpXU1VZM1RYZGxlRWMxVG5jaWZTd2lZWFZrSWpvaWFIUjBjSE02THk5dmRHaGxjbXBoWTJ0emIyNHVZWEJwTG5OM2VYQmxMbWx2SWl3aVpYaHdJam94TlRZME5USXhOamcxTENKcFlYUWlPakUxTmpRMU1UZ3dPRFVzSW1semN5STZJbWgwZEhCek9pOHZZWEJwTG5OM2VYQmxMbWx2SW4wLnJjS01xNkY0SGFWQk1xeHA3LTRXWGJXeWlUMm5RMS1hZVVqNTNoX3FrUFgwVTFGLVJsM1BCQ2U2VnNucVZDMEZwTmdvNDJGYUZsSUtBV3o0NXk4TDhWQ3hKa1pIcE1od01fdUROV2lwTzZvQUllQnFkSnlmZmtVRm1kNWJLaXNLRFlueEVwd01vemxrWDJBVWVJeFpPQ1lObXJaYmNxclpPNm12amp4WFVKOWt4Z25iaXJTaVFXVlliSXhfMFFxSGxMWWxQWDNkSFRqUU9WZkp0WHNuTXBCT25oYUZKemI3RzE1T3ZUWDRqMHpPbDhuUVNPOUhLMHlKakpCSy10Tm4wOEVUVFA0Uk1BYXJGaVI1aFNOalpod1J4aUE4NG0zM3RSdk5wbnRqWUd3T1JCem5IUE81N0haWlJRU0UxY2hVZEVVQ2ZaQVFCTjFRamhpNURpUjd4ZyIsInRva2VuX3R5cGUiOiJwb3AifQ.aEg3wdYEhKEZ2Evi7nYS_Dl3utxZfDxaVawlXwOIppA37G2FpUwE14oqH8ws4hBxgrjlq_DjGnyxIcQYuE1DAiMEFzOkw0TtOPT77pQ4OmVEBwem9T0m2mzQ7dGgfD3Bj6NF9gibVwiROdQYo2GV4vWhyVdKzMx2dkD9PqaW_LApCa1aezVXCAh1NBXEXtTSKQU5rQ1TOC3D5pSduEGZM21Om3-ESEVjp8JnaNbq7yKP6nILFMef3A0n33efIM4-FK30IIZXkNReM0H8_CiEy_kql3wk4HPETsnH5tghhiwS3Njp73PALvQmebNF4PEQRKjd4Q_UtFfKVfcBzjDjmg' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/sparql-update' \
  -d 'INSERT DATA { <https://otherjackson.api.swype.io/profile/card#me> <http://www.w3.org/2006/vcard/ns#fn> "Jackson" .
 }
'
```

The logs:
```
StoreManager patchObject { query:
   NamedNode {
     termType: 'NamedNode',
     value: 'https://otherjackson.api.swype.io/profile/card#query' },
  insert:
   IndexedFormula {
     termType: 'Graph',
     statements: [ [Statement] ],
     constraints: [],
     initBindings: [],
     optional: [],
     propertyActions:
      [ '<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>': [Array],
        '<http://www.w3.org/2002/07/owl#sameAs>': [Array] ],
     classActions:
      [ '<http://www.w3.org/2002/07/owl#InverseFunctionalProperty>': [Array],
        '<http://www.w3.org/2002/07/owl#FunctionalProperty>': [Array] ],
     redirections: [],
     aliases: [],
     HTTPRedirects: [],
     subjectIndex:
      [ '<https://otherjackson.api.swype.io/profile/card#me>': [Array] ],
     predicateIndex: [ '<http://www.w3.org/2006/vcard/ns#fn>': [Array] ],
     objectIndex: [ '"Jackson"': [Array] ],
     whyIndex:
      [ '<https://otherjackson.api.swype.io/profile/card>': [Array] ],
     index: [ [Array], [Array], [Array], [Array] ],
     namespaces: {},
     features:
      [ 'sameAs', 'InverseFunctionalProperty', 'FunctionalProperty' ] } } +2ms


  app errored TypeError: iri.includes is not a function
    at new NamedNode (/home/jackson/wac-ldp/node_modules/rdflib/lib/named-node.js:56:14)
    at IndexedFormula.sym (/home/jackson/wac-ldp/node_modules/rdflib/lib/formula.js:690:14)
    at Promise (/home/jackson/wac-ldp/src/lib/rdf/StoreManager.ts:192:95)
    at new Promise (<anonymous>)
    at StoreManager.<anonymous> (/home/jackson/wac-ldp/src/lib/rdf/StoreManager.ts:191:11)
    at Generator.next (<anonymous>)
    at /home/jackson/wac-ldp/dist/lib/rdf/StoreManager.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/jackson/wac-ldp/dist/lib/rdf/StoreManager.js:3:12)
    at StoreManager.applyPatch (/home/jackson/wac-ldp/dist/lib/rdf/StoreManager.js:169:16)
    at Object.<anonymous> (/home/jackson/wac-ldp/src/lib/operationHandlers/updateBlobHandler.ts:24:50)
    at Generator.next (<anonymous>)
    at fulfilled (/home/jackson/wac-ldp/dist/lib/operationHandlers/updateBlobHandler.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7) +9ms
  app error has no resultType iri.includes is not a function TypeError: iri.includes is not a function
    at new NamedNode (/home/jackson/wac-ldp/node_modules/rdflib/lib/named-node.js:56:14)
    at IndexedFormula.sym (/home/jackson/wac-ldp/node_modules/rdflib/lib/formula.js:690:14)
    at Promise (/home/jackson/wac-ldp/src/lib/rdf/StoreManager.ts:192:95)
    at new Promise (<anonymous>)
    at StoreManager.<anonymous> (/home/jackson/wac-ldp/src/lib/rdf/StoreManager.ts:191:11)
    at Generator.next (<anonymous>)
    at /home/jackson/wac-ldp/dist/lib/rdf/StoreManager.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/jackson/wac-ldp/dist/lib/rdf/StoreManager.js:3:12)
    at StoreManager.applyPatch (/home/jackson/wac-ldp/dist/lib/rdf/StoreManager.js:169:16)
    at Object.<anonymous> (/home/jackson/wac-ldp/src/lib/operationHandlers/updateBlobHandler.ts:24:50)
    at Generator.next (<anonymous>)
    at fulfilled (/home/jackson/wac-ldp/dist/lib/operationHandlers/updateBlobHandler.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7) +0ms


  app response is { Error: error result
    at WacLdp.<anonymous> (/home/jackson/wac-ldp/src/lib/core/WacLdp.ts:138:20)
    at Generator.throw (<anonymous>)
    at rejected (/home/jackson/wac-ldp/dist/lib/core/WacLdp.js:5:65)
    at process._tickCallback (internal/process/next_tick.js:68:7) resultType: 10 } +1ms
```

**Comment by michielbdejong** [comment] 2019-08-09 11:55
Duplicate of #121

**Closed by michielbdejong** 2019-08-09 11:55 UTC
Labels: bug
